services:
  db:
    image: postgres:latest
    container_name: finance-flow-postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d
      # - postgres_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:${DB_PORT}"

  api:
    build: .
    ports:
      - "${APP_PORT}:8080"

volumes:
  postgres_data:
